import type { State } from "./types";

const today = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);
const dayOffset = (n: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return iso(d);
};

export function createSeedState(): State {
  return {
    cfg: {
      empresa: "GBR Assistência Técnica",
      sub: "Manutenção, Instalação e Automação",
      cnpj: "12.345.678/0001-90",
      tel: "(11) 98888-1234",
      cidade: "São Paulo - SP",
      metaMensal: 28000,
      metaSemanal: 6500,
      metaAnual: 336000,
      impostoMEI: 5,
      impostoNF: 4,
      deslBase: 40,
      deslKmExtra: 2.5,
      urgencial: 15,
      maquininha: {
        debito: 1.5,
        credito1: 3.5,
        credito2: 4.2,
        credito3: 4.9,
        credito4: 5.6,
        credito5: 6.3,
        credito6: 7,
        credito7: 7.7,
        credito8: 8.4,
        credito9: 9.1,
        credito10: 9.8,
        credito11: 10.5,
        credito12: 11.2,
      },
    },
    categorias: [
      "Elétrica",
      "Informática",
      "Refrigeração",
      "Eletrodomésticos",
      "Automação",
    ],
    services: [
      { id: "s1", nome: "Instalação de tomadas e disjuntores", cat: "Elétrica", tipo: "Instalação", minVal: 120, medVal: 180, maxVal: 260, material: 45, mdo: 80, tempo: "2h", dific: "Fácil", margem: 55 },
      { id: "s2", nome: "Reparo de placa eletrônica", cat: "Informática", tipo: "Técnico", minVal: 200, medVal: 320, maxVal: 480, material: 60, mdo: 150, tempo: "4h", dific: "Difícil", margem: 60 },
      { id: "s3", nome: "Manutenção de ar-condicionado split", cat: "Refrigeração", tipo: "Preventiva", minVal: 150, medVal: 220, maxVal: 300, material: 30, mdo: 90, tempo: "2h", dific: "Médio", margem: 58 },
      { id: "s4", nome: "Configuração de roteador e rede", cat: "Informática", tipo: "Consultoria", minVal: 90, medVal: 140, maxVal: 200, material: 10, mdo: 70, tempo: "1h", dific: "Fácil", margem: 62 },
      { id: "s5", nome: "Conserto de geladeira (selante/vazamento)", cat: "Eletrodomésticos", tipo: "Técnico", minVal: 220, medVal: 350, maxVal: 520, material: 80, mdo: 160, tempo: "5h", dific: "Difícil", margem: 55 },
      { id: "s6", nome: "Instalação de campainha e interfone", cat: "Elétrica", tipo: "Instalação", minVal: 110, medVal: 160, maxVal: 230, material: 40, mdo: 70, tempo: "1.5h", dific: "Fácil", margem: 57 },
      { id: "s7", nome: "Automação de portão com IoT", cat: "Automação", tipo: "Instalação", minVal: 380, medVal: 600, maxVal: 900, material: 150, mdo: 250, tempo: "6h", dific: "Especialista", margem: 64 },
      { id: "s8", nome: "Diagnóstico técnico completo", cat: "Elétrica", tipo: "Consultoria", minVal: 60, medVal: 90, maxVal: 130, material: 0, mdo: 60, tempo: "1h", dific: "Médio", margem: 70 },
    ],
    orc: [
      { id: "o1", cliente: "Mercado Central", tel: "(11) 97777-0001", end: "Av. Brasil, 400", tipo: "Elétrica", data: dayOffset(-2), valor: 1280, status: "Faturado", lucro: 720, tempo: "1 dia", itens: [{ nome: "Instalação de tomadas e disjuntores", qtd: 6, valor: 180 }], obs: "Cliente VIP, pagamento via PIX." },
      { id: "o2", cliente: "Clínica Vida", tel: "(11) 97777-0002", end: "R. das Flores, 12", tipo: "Refrigeração", data: dayOffset(-1), valor: 660, status: "Aprovado", lucro: 360, tempo: "2h", itens: [{ nome: "Manutenção de ar-condicionado split", qtd: 3, valor: 220 }], obs: "Agendar para terça-feira." },
      { id: "o3", cliente: "João Pereira", tel: "(11) 97777-0003", end: "R. Lima, 88", tipo: "Informática", data: dayOffset(0), valor: 320, status: "Aguardando", lucro: 180, tempo: "4h", itens: [{ nome: "Reparo de placa eletrônica", qtd: 1, valor: 320 }], obs: "Aguardando aprovação do orçamento." },
      { id: "o4", cliente: "Padaria Pão Quente", tel: "(11) 97777-0004", end: "R. do Comércio, 5", tipo: "Eletrodomésticos", data: dayOffset(1), valor: 350, status: "Aprovado", lucro: 200, tempo: "5h", itens: [{ nome: "Conserto de geladeira", qtd: 1, valor: 350 }], obs: "Urgente: equipamento parado." },
      { id: "o5", cliente: "Ana Souza", tel: "(11) 97777-0005", end: "Al. Santos, 200", tipo: "Automação", data: dayOffset(-3), valor: 600, status: "Recusado", lucro: 0, tempo: "6h", itens: [{ nome: "Automação de portão com IoT", qtd: 1, valor: 600 }], obs: "Cliente achou caro, negociar." },
      { id: "o6", cliente: "Escritório Lima", tel: "(11) 97777-0006", end: "R. Vergueiro, 1000", tipo: "Informática", data: dayOffset(-5), valor: 280, status: "Faturado", lucro: 170, tempo: "1h", itens: [{ nome: "Configuração de roteador e rede", qtd: 2, valor: 140 }], obs: "Recomendou para outros colegas." },
    ],
    clientes: [
      { id: "c1", nome: "Mercado Central", tel: "(11) 97777-0001", end: "Av. Brasil, 400", email: "contato@mercadocentral.com", tipo: "VIP", origem: "Indicação", servicos: "Elétrica, Automação", gasto: 8400, nps: 5, depoimento: "Serviço impecável e sempre no prazo!", followupData: dayOffset(3), followupStatus: "Pendente", equipamentos: ["Quadro de distribuição", "Portão automático"], contratos: ["Manutenção preventiva mensal"], historico: [{ data: dayOffset(-30), texto: "Instalação completa do quadro elétrico." }, { data: dayOffset(-2), texto: "Orçamento faturado de R$ 1.280." }], obs: "Prioridade máxima." },
      { id: "c2", nome: "Clínica Vida", tel: "(11) 97777-0002", end: "R. das Flores, 12", email: "manutencao@clinicavida.com", tipo: "Recorrente", origem: "Google", servicos: "Refrigeração", gasto: 5200, nps: 5, depoimento: "Equipe pontual e profissional.", followupData: dayOffset(-1), followupStatus: "Atrasado", equipamentos: ["3x Ar-condicionado split"], contratos: [], historico: [{ data: dayOffset(-15), texto: "Manutenção dos splits." }], obs: "" },
      { id: "c3", nome: "João Pereira", tel: "(11) 97777-0003", end: "R. Lima, 88", email: "joao@email.com", tipo: "Novo", origem: "Instagram", servicos: "Informática", gasto: 0, nps: 4, depoimento: "", followupData: dayOffset(0), followupStatus: "Pendente", equipamentos: ["Notebook Dell"], contratos: [], historico: [], obs: "Primeiro atendimento." },
      { id: "c4", nome: "Padaria Pão Quente", tel: "(11) 97777-0004", end: "R. do Comércio, 5", email: "paoquente@email.com", tipo: "Recorrente", origem: "Indicação", servicos: "Eletrodomésticos", gasto: 3100, nps: 4, depoimento: "Resolveu rápido uma emergência.", followupData: dayOffset(7), followupStatus: "Pendente", equipamentos: ["Geladeira comercial"], contratos: [], historico: [{ data: dayOffset(-10), texto: "Conserto de geladeira." }], obs: "" },
      { id: "c5", nome: "Ana Souza", tel: "(11) 97777-0005", end: "Al. Santos, 200", email: "ana@email.com", tipo: "Novo", origem: "Facebook", servicos: "Automação", gasto: 0, nps: 3, depoimento: "", followupData: dayOffset(-2), followupStatus: "Atrasado", equipamentos: [], contratos: [], historico: [], obs: "Orçamento recusado, tentar renegociar." },
      { id: "c6", nome: "Escritório Lima Advocacia", tel: "(11) 97777-0006", end: "R. Vergueiro, 1000", email: "ti@limaadv.com", tipo: "VIP", origem: "Indicação", servicos: "Informática", gasto: 6700, nps: 5, depoimento: "Rede ficou estável e rápida.", followupData: dayOffset(10), followupStatus: "Pendente", equipamentos: ["Servidor", "8 pontos de rede"], contratos: ["Suporte mensal de TI"], historico: [{ data: dayOffset(-5), texto: "Configuração completa de rede." }], obs: "" },
    ],
    leads: [
      { id: "l1", nome: "Restaurante Sabor", tel: "(11) 96666-0001", interesse: "Automação de iluminação", origem: "Instagram", status: "Proposta enviada", valorEst: 1500, obs: "Quer reduzir conta de energia.", data: dayOffset(-4) },
      { id: "l2", nome: "Carlos Mendes", tel: "(11) 96666-0002", interesse: "Manutenção de split", origem: "Google", status: "Negociando", valorEst: 660, obs: "3 aparelhos para revisar.", data: dayOffset(-2) },
      { id: "l3", nome: "Academia FitPro", tel: "(11) 96666-0003", interesse: "Instalação elétrica completa", origem: "Indicação", status: "Primeiro contato", valorEst: 3200, obs: "Reforma em andamento.", data: dayOffset(-1) },
      { id: "l4", nome: "Mariana Lopes", tel: "(11) 96666-0004", interesse: "Configuração de rede", origem: "Facebook", status: "Fechado Ganho", valorEst: 280, obs: "Convertido em cliente.", data: dayOffset(-6) },
    ],
    os: [
      { id: "os1", numero: "OS-0001", cliente: "Padaria Pão Quente", tel: "(11) 97777-0004", emailCliente: "paoquente@email.com", endereco: "R. do Comércio, 5", equipamento: "Geladeira comercial", marca: "Consul", modelo: "CVT30", tipo: "Eletrodomésticos", prioridade: "Urgente", problema: "Não gela, motor quente.", diagnostico: "Vazamento de gás e termostato danificado.", solucao: "Recarga de gás + troca do termostato.", pecas: "Termostato universal, gás R134a", status: "Em Execução", valor: 350, data: dayOffset(-1), prazo: dayOffset(1), obs: "Cliente aguardando, prioridade alta.", origem: "interno", criadaEm: dayOffset(-2), fotos: [], historico: [{ data: dayOffset(-2), texto: "OS aberta via orçamento aprovado." }, { data: dayOffset(-1), texto: "Iniciado diagnóstico." }] },
      { id: "os2", numero: "OS-0002", cliente: "João Pereira", tel: "(11) 97777-0003", emailCliente: "joao@email.com", endereco: "R. Lima, 88", equipamento: "Notebook Dell", marca: "Dell", modelo: "Inspiron 15", tipo: "Informática", prioridade: "Normal", problema: "Não liga.", diagnostico: "", solucao: "", pecas: "", status: "Diagnóstico", valor: 320, data: dayOffset(0), prazo: dayOffset(4), obs: "", origem: "interno", criadaEm: dayOffset(0), fotos: [], historico: [{ data: dayOffset(0), texto: "OS aberta, equipamento recebido." }] },
      { id: "os3", numero: "OS-0003", cliente: "Cliente Online", tel: "(11) 95555-0001", emailCliente: "online@email.com", endereco: "R. Web, 1", equipamento: "TV LED 50\"", marca: "Samsung", modelo: "UN50", tipo: "Elétrica", prioridade: "Normal", problema: "Sem imagem, som normal.", diagnostico: "", solucao: "", pecas: "", status: "Aberta", valor: 0, data: dayOffset(0), prazo: dayOffset(7), obs: "Chamado aberto pelo cliente via formulário online.", origem: "cliente", criadaEm: dayOffset(0), fotos: [], historico: [{ data: dayOffset(0), texto: "Chamado recebido automaticamente (origem: cliente)." }] },
      { id: "os4", numero: "OS-0004", cliente: "Cliente Online", tel: "(11) 95555-0002", emailCliente: "online2@email.com", endereco: "R. Web, 2", equipamento: "Micro-ondas", marca: "Electrolux", modelo: "MEF41", tipo: "Eletrodomésticos", prioridade: "Alta", problema: "Esquenta mas não gira o prato.", diagnostico: "", solucao: "", pecas: "", status: "Aberta", valor: 0, data: dayOffset(0), prazo: dayOffset(7), obs: "Chamado online, aguardando triagem.", origem: "cliente", criadaEm: dayOffset(0), fotos: [], historico: [{ data: dayOffset(0), texto: "Chamado recebido (origem: cliente)." }] },
      { id: "os5", numero: "OS-0005", cliente: "Mercado Central", tel: "(11) 97777-0001", emailCliente: "contato@mercadocentral.com", endereco: "Av. Brasil, 400", equipamento: "Quadro de distribuição", marca: "-", modelo: "Trifásico", tipo: "Elétrica", prioridade: "Normal", problema: "Disjuntor desarmando.", diagnostico: "Sobrecarga em um dos circuitos.", solucao: "Redistribuição de carga e troca de disjuntor.", pecas: "Disjuntor 32A", status: "Aguardando Peça", valor: 480, data: dayOffset(-3), prazo: dayOffset(2), obs: "", origem: "interno", criadaEm: dayOffset(-4), fotos: [], historico: [{ data: dayOffset(-4), texto: "OS aberta." }, { data: dayOffset(-3), texto: "Aguardando chegada do disjuntor." }] },
      { id: "os6", numero: "OS-0006", cliente: "Clínica Vida", tel: "(11) 97777-0002", emailCliente: "manutencao@clinicavida.com", endereco: "R. das Flores, 12", equipamento: "Ar-condicionado split", marca: "LG", modelo: "S4", tipo: "Refrigeração", prioridade: "Normal", problema: "Vazamento de água.", diagnostico: "Dreno entupido.", solucao: "Limpeza e desobstrução do dreno.", pecas: "-", status: "Concluída", valor: 220, data: dayOffset(-6), prazo: dayOffset(-4), obs: "", origem: "interno", criadaEm: dayOffset(-7), fotos: [], historico: [{ data: dayOffset(-7), texto: "OS aberta." }, { data: dayOffset(-6), texto: "Serviço concluído." }] },
      { id: "os7", numero: "OS-0007", cliente: "Escritório Lima", tel: "(11) 97777-0006", emailCliente: "ti@limaadv.com", endereco: "R. Vergueiro, 1000", equipamento: "Servidor de rede", marca: "Dell", modelo: "PowerEdge", tipo: "Informática", prioridade: "Alta", problema: "Rede lenta e instável.", diagnostico: "Configuração incorreta de VLAN.", solucao: "Reconfiguração de rede e VLANs.", pecas: "-", status: "Entregue", valor: 280, data: dayOffset(-8), prazo: dayOffset(-5), obs: "", origem: "interno", criadaEm: dayOffset(-9), fotos: [], historico: [{ data: dayOffset(-9), texto: "OS aberta." }, { data: dayOffset(-5), texto: "Equipamento entregue ao cliente." }] },
      { id: "os8", numero: "OS-0008", cliente: "Ana Souza", tel: "(11) 97777-0005", emailCliente: "ana@email.com", endereco: "Al. Santos, 200", equipamento: "Portão automático", marca: "Garen", modelo: "Deslizante", tipo: "Automação", prioridade: "Normal", problema: "Cliente desistiu do serviço.", diagnostico: "", solucao: "", pecas: "", status: "Cancelada", valor: 0, data: dayOffset(-3), prazo: dayOffset(0), obs: "Cancelada pelo cliente.", origem: "interno", criadaEm: dayOffset(-4), fotos: [], historico: [{ data: dayOffset(-4), texto: "OS aberta." }, { data: dayOffset(-3), texto: "Cancelada a pedido do cliente." }] },
    ],
    garantias: [
      { id: "g1", cliente: "Mercado Central", servico: "Instalação do quadro elétrico", dataServico: dayOffset(-80), diasGarantia: 90, obs: "Garantia de instalação." },
      { id: "g2", cliente: "Clínica Vida", servico: "Manutenção dos splits", dataServico: dayOffset(-15), diasGarantia: 90, obs: "" },
      { id: "g3", cliente: "Escritório Lima", servico: "Configuração de rede", dataServico: dayOffset(-5), diasGarantia: 60, obs: "Garantia de configuração." },
    ],
    estoque: [
      { id: "e1", nome: "Disjuntor 32A", cat: "Elétrica", qtd: 4, qtdMin: 5, unidade: "un", custo: 28, local: "Prateleira A1", fornecedor: "Eletro Center", obs: "" },
      { id: "e2", nome: "Termostato universal", cat: "Refrigeração", qtd: 2, qtdMin: 3, unidade: "un", custo: 45, local: "Prateleira B2", fornecedor: "Refri Parts", obs: "" },
      { id: "e3", nome: "Gás R134a (recarga)", cat: "Refrigeração", qtd: 0, qtdMin: 2, unidade: "kg", custo: 90, local: "Armário C", fornecedor: "Refri Parts", obs: "EM FALTA — repor urgente." },
      { id: "e4", nome: "Cabo de rede CAT6", cat: "Informática", qtd: 120, qtdMin: 50, unidade: "m", custo: 3.5, local: "Caixa 4", fornecedor: "InfoTech", obs: "" },
      { id: "e5", nome: "Tomada padrão 2P+T", cat: "Elétrica", qtd: 18, qtdMin: 10, unidade: "un", custo: 8, local: "Prateleira A2", fornecedor: "Eletro Center", obs: "" },
      { id: "e6", nome: "Capacitor de partida", cat: "Eletrodomésticos", qtd: 1, qtdMin: 4, unidade: "un", custo: 22, local: "Prateleira B1", fornecedor: "Refri Parts", obs: "" },
      { id: "e7", nome: "Fita isolante (rolo)", cat: "Elétrica", qtd: 25, qtdMin: 10, unidade: "un", custo: 4, local: "Gaveta 1", fornecedor: "Eletro Center", obs: "" },
      { id: "e8", nome: "Módulo relé IoT", cat: "Automação", qtd: 3, qtdMin: 3, unidade: "un", custo: 65, local: "Armário D", fornecedor: "Smart Home BR", obs: "" },
    ],
    movEstoque: [
      { data: dayOffset(-3), item: "Disjuntor 32A", tipo: "Saída", qtd: 1, unidade: "un", obs: "OS-0005" },
      { data: dayOffset(-6), item: "Gás R134a (recarga)", tipo: "Saída", qtd: 2, unidade: "kg", obs: "OS-0001" },
      { data: dayOffset(-10), item: "Cabo de rede CAT6", tipo: "Entrada", qtd: 100, unidade: "m", obs: "Compra InfoTech" },
    ],
    agenda: [
      { id: "a1", dia: dayOffset(0), titulo: "Visita — Padaria Pão Quente", hora: "09:00", status: "Confirmado", tipo: "Serviço", obs: "Levar termostato." },
      { id: "a2", dia: dayOffset(0), titulo: "Orçamento — Academia FitPro", hora: "14:00", status: "Aguardando", tipo: "Orçamento", obs: "Avaliar reforma elétrica." },
      { id: "a3", dia: dayOffset(1), titulo: "Entrega — Escritório Lima", hora: "11:00", status: "Confirmado", tipo: "Serviço", obs: "" },
      { id: "a4", dia: dayOffset(2), titulo: "Reunião comercial — Restaurante Sabor", hora: "16:00", status: "Aguardando", tipo: "Comercial", obs: "Proposta de automação." },
      { id: "a5", dia: dayOffset(3), titulo: "Follow-up — Mercado Central", hora: "10:00", status: "Confirmado", tipo: "Comercial", obs: "Pós-venda." },
      { id: "a6", dia: dayOffset(5), titulo: "Manutenção preventiva mensal", hora: "08:30", status: "Confirmado", tipo: "Instalação", obs: "Contrato recorrente." },
    ],
    gastos: [
      { id: "x1", desc: "Compra de peças (Refri Parts)", valor: 820, data: dayOffset(-4), cat: "Materiais" },
      { id: "x2", desc: "Combustível da semana", valor: 240, data: dayOffset(-3), cat: "Transporte" },
      { id: "x3", desc: "Anúncios Instagram", valor: 150, data: dayOffset(-5), cat: "Marketing" },
      { id: "x4", desc: "DAS (MEI)", valor: 71, data: dayOffset(-6), cat: "Impostos" },
      { id: "x5", desc: "Ferramenta nova (multímetro)", valor: 180, data: dayOffset(-2), cat: "Ferramentas" },
      { id: "x6", desc: "Conta de luz (oficina)", valor: 210, data: dayOffset(-1), cat: "Operacional" },
    ],
    recExtras: [
      { id: "r1", desc: "Consultoria técnica avulsa", valor: 300, data: dayOffset(-5), cat: "Consultoria" },
      { id: "r2", desc: "Comissão por indicação", valor: 120, data: dayOffset(-2), cat: "Indicações" },
    ],
    notas: [
      { id: "n1", titulo: "Prioridades do dia", texto: "Finalizar OS-0001 (Padaria). Cobrar resposta do orçamento da Academia.", cor: "roxo", fixada: true, data: dayOffset(0), checklist: [{ id: "ck1", texto: "Finalizar OS da padaria", ok: false }, { id: "ck2", texto: "Cobrar Academia FitPro", ok: false }, { id: "ck3", texto: "Repor gás R134a", ok: true }] },
      { id: "n2", titulo: "Fornecedores", texto: "Refri Parts: (11) 9333-0001. InfoTech: (11) 9333-0002. Negociar desconto no próximo pedido.", cor: "turquesa", fixada: false, data: dayOffset(-1), checklist: [] },
      { id: "n3", titulo: "Ideias de crescimento", texto: "Criar pacote de manutenção preventiva mensal recorrente. Investir em SEO local.", cor: "rosa", fixada: false, data: dayOffset(-2), checklist: [{ id: "ck4", texto: "Definir preço do pacote", ok: false }] },
    ],
    nextOrc: 7,
    nextOS: 9,
    nextCli: 7,
    nextAg: 7,
    nextLead: 5,
    nextGar: 4,
    nextNota: 4,
    nextRecExtra: 3,
    nextGasto: 7,
    nextEst: 9,

    page: "dashboard",
    crmTab: "clientes",
    estTab: "itens",
    finTab: "geral",
    osTab: "todas",
    srvQ: "",
    srvCat: "todas",
    orcQ: "",
    cliQ: "",
    estQ: "",
    leadQ: "",
    osQ: "",
    calcItems: [],
    calcMode: "med",
    calcDesc: 0,
    calcUrg: 0,
    calcDesl: 0,
    calcCom: 0,
  };
}
